### ISSUE TITLE
Sonos

### ISSUE THREAD

**Issue by cbho** [swttt/com.swttt.devicegroups#1]
When adding Sonos components, it is only possible to choose one capability.

After selecting device class, the window changes to:
"Select devices to group" and shows a line "{{device.name}}"

If only one capability is checked, it continues to show all (the right) devices and it is possible to select 
which should be grouped.
If more than one capability is checked, no devices are available.

(And faboulous idea, btw - something Homey should be able to by itself...)

**Comment by swttt** [comment]
I guess you tried to add it as a speaker.
What capabilities did you select? Since it might have not found any devices matching the capabilities.

**Comment by cbho** [comment]
Hi,
Tried as ”amplifier” first, tried with ”speaker” as well.
Result as below.

1) When checking more than one capability:

![1](https://user-images.githubusercontent.com/29979509/29522290-fc3a41e4-8688-11e7-970a-fb99554928d9.jpg)
![2](https://user-images.githubusercontent.com/29979509/29522293-fe43e8b4-8688-11e7-8239-cbcf7b75ca51.jpg)
![3](https://user-images.githubusercontent.com/29979509/29522296-ffd788d4-8688-11e7-8155-f5258b59b145.jpg)

2) When checking only one:
![4](https://user-images.githubusercontent.com/29979509/29522300-03128166-8689-11e7-8343-da45e47bf4cb.jpg)
![5](https://user-images.githubusercontent.com/29979509/29522316-0b98c94e-8689-11e7-8633-6233307c047c.jpg)
![6](https://user-images.githubusercontent.com/29979509/29522321-0df514a4-8689-11e7-82c2-87d2eb47bc6f.jpg)

And device added – but only with the checked capability.

Regards,
Chr.

**Comment by swttt** [comment]
Can't see the images.
But the following capabilities should work:
`"capabilities": [
				"speaker_playing",
				"speaker_prev",
				"speaker_next",
				"volume_set",
				"volume_mute"
			]`

**Comment by swttt** [comment]
Aah can click the images now...
But ye the problem is you selected capabilities that don't match the device.
