### ISSUE TITLE
Grouped Devices after Reboot or Ptp

### ISSUE THREAD

**Issue by CyberSponk** [swttt/com.swttt.devicegroups#7]
Homey 1.5.3 + Device-Groups 1.0.0 > After Reboot or Ptp grouped Devices are shown Off and not longer On.

**Comment by swttt** [comment]
You are sure this happens after a soft reboot as well?
I can imagine it happens with a PTP, but shouldn't happen after a soft reboot...

**Comment by CyberSponk** [comment]
Found it: Only Devices after Soft-Reboot Offline witch used as "Virtual Device" (Device-Group without Devices) > We talked about this yesterday. All others working fine.

**Comment by swttt** [comment]
huhm.. so if i understand correctly: An empty device group isn't holding it's state when rebooting? But filled device groups do?

**Comment by CyberSponk** [comment]
yes. booted homey today and looked at it again > same: filled are fine, unfilled off. don‘t know what magic homey is doing. does a group looking if a device of it‘s group is on after boot? or is state holded by boot?

**Comment by swttt** [comment]
State is actually updated by homey itself.
Not sure why this happens, will test it some more myself.
